typography_spectrum: 0.6661607220303267
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.5
  lightness: 0.929993853205815
  saturation: 0.75
  rhythmicContrast: 0.25
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.208
analytics:
  google: null
  facebook: null
  twitter: null
name: Ryan Crozier
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Ryan Crozier
purpose: []
